# Generated by Django 4.0.5 on 2022-06-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_certificate_credentials_certificate_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='credentials',
            new_name='credential',
        ),
    ]
