# Generated by Django 4.0.5 on 2022-06-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_credentials_certificate_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
