# Generated by Django 4.0.5 on 2022-06-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_certificate_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('id',), 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
    ]
